# Generated by Django 3.2 on 2021-04-16 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=models.ImageField(default=1, upload_to='blog, null=True, blank=True'),
            preserve_default=False,
        ),
    ]
